"""Interface for Response Formatters."""

from abc import ABC, abstractmethod


class ResponseFormatter(ABC):
    """Abstract interface for formatting LLM responses.

    Different workflows need to format their output consistently
    (e.g., Markdown tables for comparisons, JSON for MCQs, bulleted lists for Summaries).
    """

    @abstractmethod
    def format(self, raw_response: str) -> str:
        """Format the raw LLM response.

        Args:
            raw_response: The raw string generated by the LLM.

        Returns:
            The formatted response string (e.g., cleaned markdown or JSON string).
        """
        pass
