"""add processing job stages

Revision ID: 002
Revises: 001
Create Date: 2026-07-06

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add current_stage column
    op.add_column(
        "processing_jobs",
        sa.Column(
            "current_stage",
            sa.String(length=20),
            nullable=False,
            server_default="uploaded",
        ),
    )
    op.create_index(
        op.f("ix_processing_jobs_current_stage"),
        "processing_jobs",
        ["current_stage"],
        unique=False,
    )

    # Add retry_count column with default 0
    op.add_column(
        "processing_jobs",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
    )

    # Add last_heartbeat column
    op.add_column(
        "processing_jobs",
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_processing_jobs_current_stage"), table_name="processing_jobs"
    )
    op.drop_column("processing_jobs", "current_stage")
    op.drop_column("processing_jobs", "retry_count")
    op.drop_column("processing_jobs", "last_heartbeat")
    # ### end Alembic commands ###
