"""add_document_ids_to_chat_sessions

Revision ID: ef16e53f04f2
Revises: a00e5f9d1c88
Create Date: 2026-07-18 12:58:29.524355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef16e53f04f2"
down_revision: str | None = "a00e5f9d1c88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_messages",
        "role",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("USER", "ASSISTANT", name="chatrole"),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.add_column("chat_sessions", sa.Column("document_ids", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_chat_sessions_id"), "chat_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_document_chunks_id"), "document_chunks", ["id"], unique=False)
    op.alter_column(
        "document_contents",
        "content_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("document_contents_document_id_key"), "document_contents", type_="unique"
    )
    op.drop_index(op.f("ix_document_contents_document_id"), table_name="document_contents")
    op.create_index(
        op.f("ix_document_contents_document_id"), "document_contents", ["document_id"], unique=True
    )
    op.create_index(op.f("ix_document_contents_id"), "document_contents", ["id"], unique=False)
    op.drop_column("document_contents", "metadata")
    op.alter_column(
        "documents",
        "file_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("PDF", "DOCX", "AUDIO", "VIDEO", name="filetype"),
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "processing_status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("UPLOADED", "PROCESSING", "COMPLETED", "FAILED", name="processingstatus"),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.alter_column(
        "processing_jobs",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("UPLOADED", "PROCESSING", "COMPLETED", "FAILED", name="processingstatus"),
        existing_nullable=False,
    )
    op.alter_column(
        "processing_jobs",
        "current_stage",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "UPLOADED",
            "EXTRACTING",
            "CHUNKING",
            "EMBEDDING",
            "INDEXING",
            "COMPLETED",
            "FAILED",
            name="processingstage",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'uploaded'::character varying"),
    )
    op.create_index(op.f("ix_processing_jobs_id"), "processing_jobs", ["id"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_processing_jobs_id"), table_name="processing_jobs")
    op.alter_column(
        "processing_jobs",
        "current_stage",
        existing_type=sa.Enum(
            "UPLOADED",
            "EXTRACTING",
            "CHUNKING",
            "EMBEDDING",
            "INDEXING",
            "COMPLETED",
            "FAILED",
            name="processingstage",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'uploaded'::character varying"),
    )
    op.alter_column(
        "processing_jobs",
        "status",
        existing_type=sa.Enum(
            "UPLOADED", "PROCESSING", "COMPLETED", "FAILED", name="processingstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.alter_column(
        "documents",
        "processing_status",
        existing_type=sa.Enum(
            "UPLOADED", "PROCESSING", "COMPLETED", "FAILED", name="processingstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "file_type",
        existing_type=sa.Enum("PDF", "DOCX", "AUDIO", "VIDEO", name="filetype"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.add_column(
        "document_contents",
        sa.Column(
            "metadata", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_document_contents_id"), table_name="document_contents")
    op.drop_index(op.f("ix_document_contents_document_id"), table_name="document_contents")
    op.create_index(
        op.f("ix_document_contents_document_id"), "document_contents", ["document_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("document_contents_document_id_key"),
        "document_contents",
        ["document_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "document_contents",
        "content_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_document_chunks_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_chat_sessions_id"), table_name="chat_sessions")
    op.drop_column("chat_sessions", "document_ids")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.alter_column(
        "chat_messages",
        "role",
        existing_type=sa.Enum("USER", "ASSISTANT", name="chatrole"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
